export const PLANS = [
  {
    id: "starter",
    name: "Starter",
    price: 30,
    credits: 3,
    discount: 0,
    features: [
      "3 Mock Interviews",
      "Email Support",
      "Community Access",
      "Basic Performance Insights",
    ],
    popular: false,
    color: "bg-blue-50",
    textColor: "text-blue-600",
  },
  {
    id: "basic",
    name: "Basic",
    price: 100,
    discount: 10,
    credits: 10,
    features: [
      "10 Mock Interviews",
      "Priority Email Support",
      "Performance Analytics",
      "Custom Interview Modes",
    ],
    popular: false,
    color: "bg-purple-50",
    textColor: "text-purple-600",
  },
  {
    id: "pro",
    name: "Advance",
    price: 500,
    discount: 20,
    credits: 50,
    features: [
      "50 Mock Interviews",
      "Real-Time AI Feedback",
      "Detailed Progress Reports",
      "24/7 Chat Support",
    ],
    popular: true,
    color: "bg-green-50",
    textColor: "text-green-600",
  },
  {
    id: "premium",
    name: "Premium",
    price: 1000,
    credits: 100,
    discount: 30,
    features: [
      "100 Mock Interviews",
      "Priority 24/7 Support",
      "Custom Feedback Reports",
      "Early Access to New Tools",
    ],
    popular: false,
    color: "bg-yellow-50",
    textColor: "text-yellow-600",
  },
];
